version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: peta-faskes-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    networks:
      - faskes-net

  nginx:
    image: nginx:alpine
    container_name: peta-faskes-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - faskes-net

networks:
  faskes-net:
    driver: bridge
